version: '2'

services:
    drupal-service:
        image: drupal
        ports:
            - '8080:80'
        volumes:
            - /var/www/html/modules
            - /var/www/html/profiles
            - /var/www/html/themes
            - /var/www/html/sites
    postgres-service:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'drupal'
            
        